allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    if (project.name == "flutter_credit_card") {
        project.pluginManager.withPlugin("com.android.library") {
            project.androidComponents.finalizeDsl { extension ->
                extension.compileSdk = 36
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
